services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
       - "1883:1883"
       - "9001:9001"
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/config/pwfile:/mosquitto/config/pwfile
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    security_opt:
      - no-new-privileges:true